name: PR Labeler

on:
  # test run this action at every 5 mins. would be changed to a specific time of a day like 9:00AM
  # now, just one time works again after 5 mins of the previous pr created
  schedule:
    - cron: "00 9 * * 1,2,3,4,5"
      branches:
        - master
  pull_request:
    types: [opened]
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
