name: PR Labeler

on:
  # UTC is 9 hours behind Seoul. It is set to run at 3PM from Sunday to Thursday considering Time Difference
  # @todo: This will be improved for global users
  schedule:
    # - cron: "00 15 * * 0,1,2,3,4"
    # - cron: "00 21 * * 0,1,2,3,4"
    - cron: "45 00 * * 0,1,2,3,4"
    - cron: "50 00 * * 0,1,2,3,4"
    - cron: "55 00 * * 0,1,2,3,4"
    - cron: "00 01 * * 0,1,2,3,4"
    - cron: "05 01 * * 0,1,2,3,4"
    - cron: "10 01 * * 0,1,2,3,4"
    - cron: "15 01 * * 0,1,2,3,4"
      branches:
        - master
  pull_request:
    types: [opened]
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
